postgres:
      image: postgres:latest
      container_name: database
      ports:
            - "5432:5432"
      environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres